Update Readme.md
coala/landing-frontend pull request #281
Opened 2018-06-19 09:15 UTC by sagban

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

2018-06-22 02:28 UTC, jayvdb commented
@gitmate-bot rebase

2018-06-22 17:55 UTC, jschwarzwalder approved these changes

2018-06-23 10:49 UTC, sagban commented
@jayvdb can you assigned me some work? According to newcomer guide, now I should work on difficulty/low issue.

2018-06-24 05:07 UTC, Hori75 approved these changes

2018-06-30 11:10 UTC, hizkifw approved these changes

2018-07-28 19:35 UTC, jayvdb requested changes

2018-07-28 19:35 UTC, jayvdb commented on README.md
> +    $ python2 -m SimpleHTTPServer 8080 #For python 2.x
We dont want to recommend people use `python2`

People should only use python3 now

2018-07-28 19:35 UTC, jayvdb commented on README.md
> +This is the coala frontend Landing Page which uses - https://gitlab.com/coala/landing as its backend.
This repository is the https://coala.io/ website frontend.
It uses https://gitlab.com/coala/landing as its backend.

2023-03-19 06:12 UTC, closed without merging